[book]
authors = ["Embedded Rust Tutorial Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Embedded Rust Tutorial for Cryptography Engineers"
description = "A streamlined guide for experienced embedded cryptography C programmers transitioning to Rust"

[preprocessor.links]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
copy-fonts = true
mathjax-support = true
git-repository-url = "https://github.com/your-repo/embedded-rust-tutorial"
edit-url-template = "https://github.com/your-repo/embedded-rust-tutorial/edit/main/{path}"
smart-punctuation = true
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js", "theme/cortex-r5-playground.js"]
cname = "embedded-rust-tutorial.github.io"
site-url = "/embedded-rust-tutorial/"

[output.html.search]
enable = true
limit-results = 50
teaser-word-count = 40
use-boolean-and = true
boost-title = 3
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
create-missing-index = true

[output.html.print]
enable = true
page-break = true

[output.html.fold]
enable = false
level = 0

[output.html.playground]
copyable = true
copy-js = true
line-numbers = true
editable = false
runnable = false

[preprocessor.rust-examples]
command = "mdbook-rust-examples"
renderer = ["html"]

[preprocessor.rust-examples.config]
embedded-target = "thumbv7em-none-eabihf"
no-std-mode = true
feature-gates = ["crypto", "hardware", "embedded"]
validation-enabled = true
compilation-timeout = 30
cache-enabled = true
