[book]
authors = ["Embedded Rust Tutorial Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Embedded Rust Tutorial for Cryptography Engineers"
description = "A streamlined guide for experienced embedded cryptography C programmers transitioning to Rust"

[preprocessor.links]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
copy-fonts = true
mathjax-support = true
git-repository-url = "https://github.com/your-repo/embedded-rust-tutorial"
edit-url-template = "https://github.com/your-repo/embedded-rust-tutorial/edit/main/{path}"
smart-punctuation = true
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
cname = "embedded-rust-tutorial.github.io"
site-url = "/embedded-rust-tutorial/"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true
page-break = true

[output.html.fold]
enable = false
level = 0

[output.html.playground]
copyable = true
copy-js = true
line-numbers = true
editable = false
runnable = false
