[target.thumbv7em-none-eabihf]
runner = "echo 'Compilation successful for thumbv7em-none-eabihf'"

[target.armv7r-none-eabihf]
runner = "echo 'Compilation successful for armv7r-none-eabihf'"

[build]
target = "thumbv7em-none-eabihf"

[unstable]
build-std = ["core"]