name: Deploy mdBook

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    
    - name: Test book build
      run: mdbook build
    
    - name: Test book content
      run: |
        # Check that key files exist in the built book
        test -f book/index.html
        test -f book/introduction.html
        test -d book/core-concepts
        test -d book/cryptography
        test -d book/embedded-patterns
        test -d book/migration
        test -d book/quick-reference
        echo "✅ Book structure validation passed"
    
    - name: Validate links (basic check)
      run: |
        # Basic validation that SUMMARY.md exists and has content
        test -s src/SUMMARY.md
        echo "✅ SUMMARY.md validation passed"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'
    
    - name: Build book
      run: mdbook build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
        cname: # Add your custom domain here if needed